server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: git
  rabbitmq:
    host: 192.168.56.38
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ojAsare910/testbank-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "458DJHWHK20392JKQP2YSAJTUWERFDJK364GVEDS6F23O7TGDEQ29OHQS9321GDQWSE"